In [1]:
import numpy as np
import tensorflow as tf
filePath = './test_case_ans/sample_case001_input.txt'
c = 3e8

def loadData(filePath):
    with open(filePath, 'r') as fd:
        station_num = int(fd.readline())
        device_num = int(fd.readline())
        dimen = int(fd.readline())
        station_cord = []
        for i in range(station_num):
            cord = fd.readline().split()
            cord = [np.float64(i) for i in cord]
            station_cord.append(cord)
        station_cord = np.array(station_cord)

        device_cord = []
        for i in range(device_num):
            cord = fd.readline().split()
            cord = [np.float64(i) for i in cord]
            device_cord.append(cord)
        device_cord = np.array(device_cord)
        return station_cord, device_cord

S, D = loadData(filePath)
device_Dist = D*c

cord_init = np.mean(S, axis=0)
cord_init = cord_init.reshape([1, 3]) * np.ones([len(D), 3])
bias_init = np.zeros(len(D))

In [6]:
cord = tf.Variable(cord_init[0:1], 'Cordinate')
bias = tf.Variable(bias_init[0:1], 'Bias')
D_dist = tf.constant(device_Dist[0:1], tf.float64)
Station = tf.constant(S, tf.float64)

expand_cord = tf.expand_dims(cord, 1)
expand_Sta = tf.expand_dims(Station, 0)
expand_bias = tf.expand_dims(bias, 1) #(N, 1)

dist_hat = tf.sqrt(tf.reduce_sum(((expand_cord - expand_Sta) ** 2), 2)) - expand_bias #(N,M)

# losses = tf.reduce_sum((dist_hat - D_dist) **2, 1)
losses = tf.reduce_sum((dist_hat - D_dist) **2)

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
train_op = optimizer.minimize(losses)

config=tf.ConfigProto()
config.gpu_options.allow_growth = True
config.allow_soft_placement = True
with tf.Session(config=config) as sess:
    sess.run(tf.initialize_all_variables())
    for i in range(10000):
        _, loss = sess.run([train_op, losses])
        if i%100 == 0:
            print np.sum(loss)
            B, P = sess.run([bias, cord])
            print P

399473.705622
[[ 25.14647939  17.28641247   3.96343608]]
163922.373401
[[ 6.62241335  9.27638259  3.97793094]]
85041.8463009
[[-6.30332424  2.68254372  3.94459347]]
59249.094026
[[-14.5181475   -2.29933246   3.88644404]]
50889.6951862
[[-19.523966    -5.86978777   3.82198915]]
48141.9302479
[[-22.53168374  -8.3575369    3.76003919]]
47206.6059504
[[-24.33685887 -10.0690781    3.70350941]]
46871.6129882
[[-25.42525796 -11.24194087   3.65282388]]
46744.2758163
[[-26.08593329 -12.04615407   3.60757046]]
46692.9029515
[[-26.48980062 -12.59912339   3.56714882]]
46671.0577232
[[-26.73820271 -12.98072031   3.53098355]]
46661.3641842
[[-26.89167076 -13.24505878   3.4985752 ]]
46656.9169618
[[-26.98670154 -13.42884573   3.46949954]]
46654.8207247
[[-27.04552153 -13.55706957   3.44339435]]
46653.8081211
[[-27.08179641 -13.64681626   3.41994632]]
46653.3061644
[[-27.1039991  -13.70982086   3.39888088]]
46653.0495456
[[-27.11741848 -13.75417736   3.37995497]]
46652.9131506
[[-27.12537172 -13.78548

In [3]:
print P[:3]
print '-------'
print B[:3]

[[ -27.1321631   -13.86313017    3.21336896]
 [ -96.52950938   47.45727083    3.2529974 ]
 [-125.36905421 -254.10818418    4.2589409 ]]
-------
[-92.90000579 -99.6475248  -94.77997866]


In [8]:
%%bash
head -30 test_case_ans/sample_case001_ans.txt

-21.19	4.48	1.48	
-81.14	58.24	1.38	
-96.13	-215.22	1.02	
-296.06	-20.15	1.59	
86.29	-111.06	1.66	
-31.26	244.68	1.30	
-286.47	-38.75	1.73	
319.30	-170.11	1.03	
-37.40	273.59	1.73	
255.34	66.63	1.21	
104.46	203.54	1.95	
-120.39	92.32	1.72	
114.52	198.68	1.33	
-315.97	-70.50	1.36	
-257.80	45.43	1.32	
-18.52	-30.78	1.57	
-313.79	16.87	1.63	
274.89	268.50	1.34	
-302.82	-282.68	1.23	
-320.15	10.09	1.81	
286.92	2.51	1.44	
-62.65	-162.18	1.50	
-147.51	-161.47	1.18	
-191.31	20.93	1.85	
-213.72	109.73	1.34	
5.46	127.88	1.04	
-218.02	113.34	1.40	
-82.92	-0.78	1.90	
13.63	322.85	1.04	
94.23	-107.05	1.18	


In [1]:
import numpy as np
import tensorflow as tf
filePath = './test_case_ans/sample_case001_input.txt'
c = 3e8

def loadData(filePath):
    with open(filePath, 'r') as fd:
        station_num = int(fd.readline())
        device_num = int(fd.readline())
        dimen = int(fd.readline())
        station_cord = []
        for i in range(station_num):
            cord = fd.readline().split()
            cord = [np.float64(i) for i in cord]
            station_cord.append(cord)
        station_cord = np.array(station_cord)

        device_cord = []
        for i in range(device_num):
            cord = fd.readline().split()
            cord = [np.float64(i) for i in cord]
            device_cord.append(cord)
        device_cord = np.array(device_cord)
        return station_cord, device_cord

S, D = loadData(filePath)
device_Dist = D*c

cord_init = np.mean(S, axis=0)
cord_init = cord_init.reshape([1, 3]) * np.ones([len(D), 3])
bias_init = np.zeros(len(D))

cord = tf.Variable(cord_init, 'Cordinate')
bias = tf.Variable(bias_init, 'Bias')
alpha = tf.Variable(np.ones((len(cord_init), 3)), 'Alpha', dtype = tf.float64)  #(N, 3)

D_dist = tf.constant(device_Dist, tf.float64)
Station = tf.constant(S, tf.float64)

expand_cord = tf.expand_dims(cord, 1)   #(N, 1, 3)
expand_Sta = tf.expand_dims(Station, 0) #(1, M, 3)
expand_bias = tf.expand_dims(bias, 1)   #(N, 1)
expand_alpha = tf.expand_dims(alpha, 1) #(N, 1, 3)

dist_hat = tf.sqrt(tf.reduce_sum(expand_alpha**2 * ((expand_cord - expand_Sta) ** 2), 2)) - expand_bias #(N,M)

losses = tf.reduce_sum((dist_hat - D_dist) **2, 1)

optimizer = tf.train.AdamOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(losses)

config=tf.ConfigProto()
config.gpu_options.allow_growth = True
config.allow_soft_placement = True
with tf.Session(config=config) as sess:
    sess.run(tf.initialize_all_variables())
    for i in range(50000):
        _, loss = sess.run([train_op, losses])
        if i%100 == 0:
            print np.sum(loss)
    B, P, al= sess.run([bias, cord, alpha])
print P[:30]
print '-------'
print B[:30]
print '-------'
print alpha[:30]

3391432620.01
1164944393.41
950594717.899
882315479.382
809868473.11
735237741.433
660363979.524
587135766.783
517172302.611
451787791.423
392063242.332
338743624.513
292058986.565
251760098.593
217307871.83
188025284.243
163205950.381
142176255.315
124327590.376
109131934.166
96143438.9172
84991606.8516
75371363.3384
67032858.2401
59772117.7164
53422784.2252
47848678.171
42937341.732
38595058.1581
34743303.1879
31316733.8917
28261579.1321
25531501.7563
23087127.1851
20897784.368
18934304.9046
17177974.3165
15602993.7984
14185425.9521
12913596.523
11775616.1643
10760237.7502
9867832.54762
9059896.9124
8364817.6509
7757207.65066
7217177.38713
6740270.89979
6332885.2789
5959799.71558
5633238.93095
5365713.25187
5118623.32861
4897806.70622
4689706.49717
4524148.80859
4374434.52076
4245333.92843
4120567.08487
3990006.34838
3902264.96953
3815511.13305
3727586.91079
3667556.63102
3598652.09519
3538583.59408
3489930.16851
3428997.80818
3411293.85344
3349914.11137
3316339.47597
3301037.88455
3

ValueError: Shape (1100, 3) must have rank 1